# Generated by Django 5.2.17 on 2026-09-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("custom_images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="custom_images.customimage",
            ),
        ),
    ]
