# Generated by Django 5.2.17 on 2026-09-25 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_setup_editor_permissions'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, help_text='개인정보처리방침 등에 노출되는 운영자 문의 이메일. 비워두면 연락처 안내를 표시하지 않는다(값이 없다고 페이지 렌더링이 깨지지 않음 — legal_page.html이 빈 값을 조건 분기로 처리).', max_length=254)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
