# Generated by Django 5.2.17 on 2026-09-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_client_id',
            field=models.CharField(blank=True, help_text="Google 애드센스 게시자 ID(예: ca-pub-1234567890123456). 애드센스 심사 승인 후 발급받은 값을 그대로 붙여넣는다. 비워두면 광고 스크립트·ads.txt·개인정보처리방침 광고 쿠키 안내 전부 렌더링되지 않는다(contact_email과 동일한 '값 없으면 조용히 비활성' 원칙 — 애드센스 계정이 없는 상태에서도 사이트가 정상 동작해야 하므로).", max_length=32),
        ),
    ]
