# Generated by Django 5.2.17 on 2026-09-16 20:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        help_text="법적 고지 본문. h2 제목마다 자동으로 목차가 생성된다."
                    ),
                ),
            ],
            options={
                "verbose_name": "법적 페이지",
                "verbose_name_plural": "법적 페이지",
            },
            bases=("wagtailcore.page",),
        ),
    ]
