# Generated by Django 5.2.17 on 2026-09-25 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_alter_blogpostpage_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='자유입력 표시명(회원가입 없음, 실명 검증 없음, 03 §3.2-1).', max_length=100)),
                ('body', models.TextField(help_text='댓글 본문(plain text만 허용 — 템플릿에서 HTML 이스케이프 후 렌더링, 03 §3.2-1 XSS 방지 원칙).')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '거부됨')], default='pending', max_length=20)),
                ('source_ip_masked', models.CharField(blank=True, help_text='스팸 판별용, 마지막 옥텟/세그먼트를 마스킹한 접속 IP(subscribers 앱과 동일 원칙).', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpostpage')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'ordering': ['created_at'],
            },
        ),
    ]
