# Generated by Django 5.2.17 on 2026-09-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_grant_moderator_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='차단할 접속 IP. 마스킹하지 않은 원본 값을 그대로 입력한다.')),
                ('reason', models.CharField(blank=True, help_text="차단 사유(선택). 자동 차단은 '자동: N일 내 반복 거부 M회' 형식으로 채워진다.", max_length=255)),
                ('is_auto', models.BooleanField(default=False, help_text='자동 차단 로직이 생성했으면 True. 운영자가 직접 추가했으면 False.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='이 시각 이후 자동으로 차단이 풀린다. 비워두면 영구 차단(수동 차단의 기본값).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '차단된 IP',
                'verbose_name_plural': '차단된 IP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='source_ip_raw',
            field=models.GenericIPAddressField(blank=True, help_text='자동 반복거부 차단 판정에만 내부적으로 쓰이는 원본 접속 IP. 어드민 화면에는 노출하지 않는다(panels 미포함, DEC-055).', null=True),
        ),
    ]
