# Generated by Django 5.2.17 on 2026-09-16 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # wagtailcore 최신 마이그레이션이 아니라 0040을 의존성으로 고정한다 — Wagtail
    # 공식 project_template(0002_create_homepage.py의 run_before=wagtailcore.0053)과
    # 동일한 패턴을 따르기 위함이다. makemigrations가 자동 생성한 최신 버전(0097)을
    # 그대로 두면 0002의 run_before 제약과 순환 의존성(CircularDependencyError)이
    # 발생한다(webapp 검증 중 실제로 재현/확인함).
    dependencies = [
        ("wagtailcore", "0040_page_draft_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
