# Generated by Django 5.2.17 on 2026-09-16 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="구독 시점에 소문자로 정규화되어 저장된다(views.py 참고).",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("consented_at", models.DateTimeField()),
                (
                    "consent_version",
                    models.CharField(
                        help_text="동의 시점의 개인정보처리방침 버전 스냅샷(constants.PRIVACY_POLICY_VERSION).",
                        max_length=50,
                    ),
                ),
                (
                    "source_ip_masked",
                    models.CharField(
                        blank=True,
                        help_text="스팸 판별용, 마지막 옥텟/세그먼트를 마스킹한 접속 IP.",
                        max_length=45,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "구독중"), ("unsubscribed", "구독취소")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "뉴스레터 구독자",
                "verbose_name_plural": "뉴스레터 구독자",
                "ordering": ["-created_at"],
            },
        ),
    ]
